name: Lint & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  lint-and-test:
    name: "Lint & Test"
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12", "3.13"] # "3.14" omitted due to issues with some deps
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install ".[track_tags,waveform_drawing,beatgrid_analysis]"
        python -m pip install pylint

    - name: Lint (Pylint)
      run: pylint $(git ls-files '*.py')

    - name: Lint (PyRight)
      uses: jakebailey/pyright-action@v1
      with:
        working-directory: .

    - name: Format Check (Black)
      uses: psf/black@stable

    - name: Test
      run: python -m unittest